# Generated by Django 2.0 on 2020-02-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200223_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='planning',
            field=models.TextField(default='defalut value'),
            preserve_default=False,
        ),
    ]
