# Generated by Django 2.0 on 2020-02-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=500)),
                ('audience', models.CharField(max_length=500)),
                ('session_date', models.DateTimeField()),
            ],
        ),
    ]
