# Generated by Django 2.0 on 2020-02-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
