# Generated by Django 2.0 on 2020-02-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0002_session_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_content',
            field=models.TextField(default='Sessions'),
            preserve_default=False,
        ),
    ]
