# Generated by Django 2.0 on 2020-02-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0003_session_session_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(default='sluggish', unique=True),
            preserve_default=False,
        ),
    ]
