# Generated by Django 2.0 on 2020-02-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0005_remove_session_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(default='sluglish', unique=True),
            preserve_default=False,
        ),
    ]
