# Generated by Django 2.0 on 2020-03-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0006_session_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='booked_no',
            field=models.IntegerField(default=1),
        ),
    ]
