# Generated by Django 2.0 on 2020-03-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200315_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Working_ScreenShots',
            field=models.ImageField(blank=True, null=True, upload_to='Working_ScreenShots'),
        ),
    ]
