# Generated by Django 2.0 on 2020-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200317_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
