# Generated by Django 2.0 on 2020-03-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='liked',
            new_name='likes',
        ),
    ]
