# Generated by Django 2.0 on 2020-03-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200318_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='numb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='numb_rem',
            field=models.IntegerField(default=0),
        ),
    ]
